FROM php.8.3.0-apache
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y libonig-dev

#Extras de php
RUN docker-php-ext-install
RUN docker-php-ext-install pdo_mysql

#update
RUN apt-get update \
    && apt-get install -y libpng-dev \
    && apt-get install -y libzip-dev \
    && apt-get install -y zlib1g-dev \
    && apt-get install -y libonig-dev \
    && rm -rf /var/lib/apt/lists/* 

#Extras de php
RUN docker-php-ext-install mbstring
RUN docker-php-ext-install zip
RUN docker-php-ext-install gd

RUN a2enmod rewrite